# Project 1: Explanatory Data Analysis & Data Presentation (Movies Dataset)

# Project Brief for Self-Coders

Here you´ll have the opportunity to code major parts of Project 1 on your own. If you need any help or inspiration, have a look at the Videos or the Jupyter Notebook with the full code. <br> <br>
Keep in mind that it´s all about __getting the right results/conclusions__. It´s not about finding the identical code. Things can be coded in many different ways. Even if you come to the same conclusions, it´s very unlikely that we have the very same code.

## Data Import and first Inspection

1. __Import__ the movies dataset from the CSV file "movies_complete.csv". __Inspect__ the data.

In [168]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud

In [169]:
movies = pd.read_csv('movies_complete.csv',parse_dates=['release_date'])

In [170]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44691 entries, 0 to 44690
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     44691 non-null  int64
 1   title                  44691 non-null  object
 2   tagline                20284 non-null  object
 3   release_date           44657 non-null  datetime64[ns]
 4   genres                 42586 non-null  object
 5   belongs_to_collection  4463 non-null   object
 6   original_language      44681 non-null  object
 7   budget_musd            8854 non-null   float64
 8   revenue_musd           7385 non-null   float64
 9   production_companies   33356 non-null  object
 10  production_countries   38835 non-null  object
 11  vote_count             44691 non-null  float64
 12  vote_average           42077 non-null  float64
 13  popularity             44691 non-null  float64
 14  runtime                43179 non-null  float64
 15  overview               43740 non-null  object
 16  spoken_languages       41094 non-null  object
 17  poster_path            44467 non-null  object
 18  cast                   42502 non-null  object
 19  cast_size              44691 non-null  int64
 20  crew_size              44691 non-null  int64
 21  director               43960 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(3), object(12)
memory usage: 7.5+ MB

__Some additional information on Features/Columns__:

* **id:** The ID of the movie (clear/unique identifier).
* **title:** The Official Title of the movie.
* **tagline:** The tagline of the movie.
* **release_date:** Theatrical Release Date of the movie.
* **genres:** Genres associated with the movie.
* **belongs_to_collection:** Gives information on the movie series/franchise the particular film belongs to.
* **original_language:** The language in which the movie was originally shot in.
* **budget_musd:** The budget of the movie in million dollars.
* **revenue_musd:** The total revenue of the movie in million dollars.
* **production_companies:** Production companies involved with the making of the movie.
* **production_countries:** Countries where the movie was shot/produced in.
* **vote_count:** The number of votes by users, as counted by TMDB.
* **vote_average:** The average rating of the movie.
* **popularity:** The Popularity Score assigned by TMDB.
* **runtime:** The runtime of the movie in minutes.
* **overview:** A brief blurb of the movie.
* **spoken_languages:** Spoken languages in the film.
* **poster_path:** The URL of the poster image.
* **cast:** (Main) Actors appearing in the movie.
* **cast_size:** number of Actors appearing in the movie.
* **director:** Director of the movie.
* **crew_size:** Size of the film crew (incl. director, excl. actors).

In [171]:
movies['profit'] = movies['revenue_musd'] - movies['budget_musd']
movies['ROI'] = movies['profit'].div(movies['budget_musd'])
movies = movies.fillna(0)

## The best and the worst movies...

2. __Filter__ the Dataset and __find the best/worst n Movies__ with the

- Highest Revenue
- Highest Budget
- Highest Profit (=Revenue - Budget)
- Lowest Profit (=Revenue - Budget)
- Highest Return on Investment (=Revenue / Budget) (only movies with Budget >= 10) 
- Lowest Return on Investment (=Revenue / Budget) (only movies with Budget >= 10)
- Highest number of Votes
- Highest Rating (only movies with 10 or more Ratings)
- Lowest Rating (only movies with 10 or more Ratings)
- Highest Popularity

__Define__ an appropriate __user-defined function__ to reuse code.

__Movies Top 5 - Highest Revenue__

In [172]:
#revenueTop =  movies['revenue_musd'].sort_values(ascending=False).head(5)
#movies.iloc[revenueTop.index]

def filterMovies(df: pd.DataFrame , filterName: str, number: int, best_worst :bool,min_budget : int = 0,min_votes : int = 0):
    df_min_budget = df[df['budget_musd']>=min_budget]
    df_min_votes = df_min_budget[df_min_budget['vote_count']>min_votes]
    df_min_votes = df_min_votes.reset_index()
    filterIndex = df_min_votes[filterName].sort_values(ascending=best_worst).head(number)
    return(df_min_votes.iloc[filterIndex.index])
revenueTop = filterMovies(movies,'revenue_musd',5,False)
revenueTop

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
14204,14448,19995,Avatar,Enter the World of Pandora.,2009-12-10 00:00:00,Action|Adventure|Fantasy|Science Fiction,Avatar Collection,en,237.0,2787.965087,...,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español,<img src='http://image.tmdb.org/t/p/w185//btnl...,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,83,153,James Cameron,2550.965087,10.763566
25303,26265,140607,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15 00:00:00,Action|Adventure|Science Fiction|Fantasy,Star Wars Collection,en,245.0,2068.223624,...,136.0,Thirty years after defeating the Galactic Empi...,English,<img src='http://image.tmdb.org/t/p/w185//9rd0...,Daisy Ridley|John Boyega|Adam Driver|Harrison ...,84,113,J.J. Abrams,1823.223624,7.441729
1561,1620,597,Titanic,Nothing on Earth could come between them.,1997-11-18 00:00:00,Drama|Romance|Thriller,0,en,200.0,1845.034188,...,194.0,"84 years later, a 101-year-old woman named Ros...",English|Français|Deutsch|svenska|Italiano|Pусский,<img src='http://image.tmdb.org/t/p/w185//9xjZ...,Kate Winslet|Leonardo DiCaprio|Frances Fisher|...,136,65,James Cameron,1645.034188,8.225171
17311,17669,24428,The Avengers,Some assembly required.,2012-04-25 00:00:00,Science Fiction|Action|Adventure,The Avengers Collection,en,220.0,1519.557910,...,143.0,When an unexpected enemy emerges and threatens...,English,<img src='http://image.tmdb.org/t/p/w185//RYMX...,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,115,147,Joss Whedon,1299.557910,5.907081
23962,24812,135397,Jurassic World,The park is open.,2015-06-09 00:00:00,Action|Adventure|Science Fiction|Thriller,Jurassic Park Collection,en,150.0,1513.528810,...,124.0,Twenty-two years after the events of Jurassic ...,English,<img src='http://image.tmdb.org/t/p/w185//rhr4...,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,28,435,Colin Trevorrow,1363.528810,9.090192

__Movies Top 5 - Highest Budget__

In [173]:
budget = filterMovies(movies,'budget_musd',5,False)
budget

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
16657,16986,1865,Pirates of the Caribbean: On Stranger Tides,Live Forever Or Die Trying.,2011-05-14 00:00:00,Adventure|Action|Fantasy,Pirates of the Caribbean Collection,en,380.0,1045.713802,...,136.0,Captain Jack Sparrow crosses paths with a woma...,English|Español,<img src='http://image.tmdb.org/t/p/w185//keGf...,Johnny Depp|Penélope Cruz|Ian McShane|Kevin Mc...,36,39,Rob Marshall,665.713802,1.751878
11555,11743,285,Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.",2007-05-19 00:00:00,Adventure|Fantasy|Action,Pirates of the Caribbean Collection,en,300.0,961.000000,...,169.0,"Captain Barbossa, long believed to be dead, ha...",English,<img src='http://image.tmdb.org/t/p/w185//oVh3...,Johnny Depp|Orlando Bloom|Keira Knightley|Stel...,34,32,Gore Verbinski,661.000000,2.203333
25306,26268,99861,Avengers: Age of Ultron,A New Age Has Come.,2015-04-22 00:00:00,Action|Adventure|Science Fiction,The Avengers Collection,en,280.0,1405.403694,...,141.0,When Tony Stark tries to jumpstart a dormant p...,English,<img src='http://image.tmdb.org/t/p/w185//4ssD...,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,72,74,Joss Whedon,1125.403694,4.019299
10803,10985,1452,Superman Returns,0,2006-06-28 00:00:00,Adventure|Fantasy|Action|Science Fiction,Superman Collection,en,270.0,391.081192,...,154.0,Superman returns to discover his 5-year absenc...,English|Français|Deutsch,<img src='http://image.tmdb.org/t/p/w185//6ZYO...,Brandon Routh|Kevin Spacey|Kate Bosworth|James...,18,24,Bryan Singer,121.081192,0.448449
18117,18517,49529,John Carter,"Lost in our world, found in another.",2012-03-07 00:00:00,Action|Adventure|Science Fiction,0,en,260.0,284.139100,...,132.0,"John Carter is a war-weary, former military ca...",English,<img src='http://image.tmdb.org/t/p/w185//7GSS...,Taylor Kitsch|Lynn Collins|Samantha Morton|Wil...,28,132,Andrew Stanton,24.139100,0.092843

__Movies Top 5 - Highest Profit__

In [174]:
profit = filterMovies(movies,'profit',5,False)
profit

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
14204,14448,19995,Avatar,Enter the World of Pandora.,2009-12-10 00:00:00,Action|Adventure|Fantasy|Science Fiction,Avatar Collection,en,237.0,2787.965087,...,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español,<img src='http://image.tmdb.org/t/p/w185//btnl...,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,83,153,James Cameron,2550.965087,10.763566
25303,26265,140607,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15 00:00:00,Action|Adventure|Science Fiction|Fantasy,Star Wars Collection,en,245.0,2068.223624,...,136.0,Thirty years after defeating the Galactic Empi...,English,<img src='http://image.tmdb.org/t/p/w185//9rd0...,Daisy Ridley|John Boyega|Adam Driver|Harrison ...,84,113,J.J. Abrams,1823.223624,7.441729
1561,1620,597,Titanic,Nothing on Earth could come between them.,1997-11-18 00:00:00,Drama|Romance|Thriller,0,en,200.0,1845.034188,...,194.0,"84 years later, a 101-year-old woman named Ros...",English|Français|Deutsch|svenska|Italiano|Pусский,<img src='http://image.tmdb.org/t/p/w185//9xjZ...,Kate Winslet|Leonardo DiCaprio|Frances Fisher|...,136,65,James Cameron,1645.034188,8.225171
23962,24812,135397,Jurassic World,The park is open.,2015-06-09 00:00:00,Action|Adventure|Science Fiction|Thriller,Jurassic Park Collection,en,150.0,1513.528810,...,124.0,Twenty-two years after the events of Jurassic ...,English,<img src='http://image.tmdb.org/t/p/w185//rhr4...,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,28,435,Colin Trevorrow,1363.528810,9.090192
27361,28501,168259,Furious 7,Vengeance Hits Home,2015-04-01 00:00:00,Action,The Fast and the Furious Collection,en,190.0,1506.249360,...,137.0,Deckard Shaw seeks revenge against Dominic Tor...,English,<img src='http://image.tmdb.org/t/p/w185//d9jZ...,Vin Diesel|Paul Walker|Dwayne Johnson|Michelle...,52,98,James Wan,1316.249360,6.927628

__Movies Top 5 - Lowest Profit__

In [175]:
profitLow = filterMovies(movies,'profit',5,True)
profitLow

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
20392,20959,57201,The Lone Ranger,Never Take Off the Mask,2013-07-03 00:00:00,Action|Adventure|Western,0,en,255.000000,89.289910,...,149.0,The Texas Rangers chase down a gang of outlaws...,English,<img src='http://image.tmdb.org/t/p/w185//b2je...,Johnny Depp|Armie Hammer|William Fichtner|Hele...,60,35,Gore Verbinski,-165.710090,-0.649843
7013,7164,10733,The Alamo,You will never forget,2004-04-07 00:00:00,Western|History|War,0,en,145.000000,25.819961,...,137.0,Based on the 1836 standoff between a group of ...,English|Español,<img src='http://image.tmdb.org/t/p/w185//aZrW...,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,20,145,John Lee Hancock,-119.180039,-0.821931
16340,16659,50321,Mars Needs Moms,Mom needs a little space.,2011-03-09 00:00:00,Adventure|Animation|Family,0,en,150.000000,38.992758,...,88.0,"When Martians suddenly abduct his mom, mischie...",English,<img src='http://image.tmdb.org/t/p/w185//lOKq...,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,12,7,Simon Wells,-111.007242,-0.740048
41098,43611,339964,Valerian and the City of a Thousand Planets,0,2017-07-20 00:00:00,Adventure|Science Fiction|Action,0,en,197.471676,90.024292,...,137.0,"In the 28th century, Valerian and Laureline ar...",Français|English,<img src='http://image.tmdb.org/t/p/w185//jfIp...,Dane DeHaan|Cara Delevingne|Clive Owen|Rihanna...,118,316,Luc Besson,-107.447384,-0.544115
2603,2684,1911,The 13th Warrior,Prey for the living.,1999-08-27 00:00:00,Adventure|Fantasy|Action,0,en,160.000000,61.698899,...,102.0,"In AD 922, Arab courtier, Ahmad Ibn Fadlan acc...",English|Norsk,<img src='http://image.tmdb.org/t/p/w185//7pyh...,Antonio Banderas|Vladimir Kulich|Dennis Storhø...,19,17,John McTiernan,-98.301101,-0.614382

In [176]:
movies_with_budget = movies[movies['budget_musd']>50]

__Movies Top 5 - Highest ROI__

In [177]:
ROI = filterMovies(movies,'ROI',5,False,50)
ROI

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
1078,30330,211672,Minions,"Before Gru, they had a history of bad bosses",2015-06-17 00:00:00,Family|Animation|Adventure|Comedy,Despicable Me Collection,en,74.0,1156.730962,...,91.0,"Minions Stuart, Kevin and Bob are recruited by...",English,<img src='http://image.tmdb.org/t/p/w185//tMaG...,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,17,12,Kyle Balda,1082.730962,14.631499
39,474,329,Jurassic Park,An adventure 65 million years in the making.,1993-06-11 00:00:00,Adventure|Science Fiction,Jurassic Park Collection,en,63.0,920.100000,...,127.0,A wealthy entrepreneur secretly creates a them...,English|Español,<img src='http://image.tmdb.org/t/p/w185//oU7O...,Sam Neill|Laura Dern|Jeff Goldblum|Richard Att...,27,118,Steven Spielberg,857.100000,13.604762
736,14323,18239,The Twilight Saga: New Moon,The Next Chapter Begins.,2009-03-15 00:00:00,Adventure|Fantasy|Drama|Romance,The Twilight Collection,en,50.0,709.827462,...,130.0,"Forks, Washington resident Bella Swan is reeli...",English|Italiano,<img src='http://image.tmdb.org/t/p/w185//j5jM...,Kristen Stewart|Robert Pattinson|Taylor Lautne...,37,26,Chris Weitz,659.827462,13.196549
1043,26272,293660,Deadpool,Witness the beginning of a happy ending,2016-02-09 00:00:00,Action|Adventure|Comedy,Deadpool Collection,en,58.0,783.112979,...,108.0,Deadpool tells the origin story of former Spec...,English,<img src='http://image.tmdb.org/t/p/w185//fSRb...,Ryan Reynolds|Morena Baccarin|Ed Skrein|T.J. M...,46,88,Tim Miller,725.112979,12.501948
939,20946,93456,Despicable Me 2,Back 2 Work,2013-06-25 00:00:00,Animation|Comedy|Family,Despicable Me Collection,en,76.0,970.761885,...,98.0,Gru is recruited by the Anti-Villain League to...,English,<img src='http://image.tmdb.org/t/p/w185//xL6t...,Steve Carell|Kristen Wiig|Benjamin Bratt|Miran...,39,31,Pierre Coffin,894.761885,11.773183

__Movies Top 5 - Lowest ROI__

In [178]:
ROILow = filterMovies(movies,'ROI',5,True,100)
ROILow

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
50,5345,11692,The Adventures of Pluto Nash,Action's future has arrived...,2002-08-15 00:00:00,Action|Comedy|Science Fiction,0,en,100.0,7.103973,...,95.0,"The year is 2087, the setting is the moon. Plu...",English,<img src='http://image.tmdb.org/t/p/w185//96vv...,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,14,9,Ron Underwood,-92.896027,-0.928960
69,7164,10733,The Alamo,You will never forget,2004-04-07 00:00:00,Western|History|War,0,en,145.0,25.819961,...,137.0,Based on the 1836 standoff between a group of ...,English|Español,<img src='http://image.tmdb.org/t/p/w185//aZrW...,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,20,145,John Lee Hancock,-119.180039,-0.821931
362,40847,259695,Live by Night,Witness the price of the American Dream.,2016-12-25 00:00:00,Crime|Drama,0,en,108.0,22.678555,...,129.0,A story set in the Prohibition Era and centere...,English|Español,<img src='http://image.tmdb.org/t/p/w185//bkd4...,Ben Affleck|Elle Fanning|Brendan Gleeson|Chris...,29,23,Ben Affleck,-85.321445,-0.790013
204,16659,50321,Mars Needs Moms,Mom needs a little space.,2011-03-09 00:00:00,Adventure|Animation|Family,0,en,150.0,38.992758,...,88.0,"When Martians suddenly abduct his mom, mischie...",English,<img src='http://image.tmdb.org/t/p/w185//lOKq...,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,12,7,Simon Wells,-111.007242,-0.740048
265,20959,57201,The Lone Ranger,Never Take Off the Mask,2013-07-03 00:00:00,Action|Adventure|Western,0,en,255.0,89.289910,...,149.0,The Texas Rangers chase down a gang of outlaws...,English,<img src='http://image.tmdb.org/t/p/w185//b2je...,Johnny Depp|Armie Hammer|William Fichtner|Hele...,60,35,Gore Verbinski,-165.710090,-0.649843

__Movies Top 5 - Most Votes__

In [179]:
votes_best = filterMovies(movies,'vote_count',5,False)
votes_best

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
15095,15368,27205,Inception,Your mind is the scene of the crime.,2010-07-14 00:00:00,Action|Thriller|Science Fiction|Mystery|Adventure,0,en,160.0,825.532764,...,148.0,"Cobb, a skilled thief who commits corporate es...",English,<img src='http://image.tmdb.org/t/p/w185//9gk7...,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,29,18,Christopher Nolan,665.532764,4.159580
12202,12396,155,The Dark Knight,Why So Serious?,2008-07-16 00:00:00,Drama|Action|Crime|Thriller,The Dark Knight Collection,en,185.0,1004.558444,...,152.0,Batman raises the stakes in his war on crime. ...,English|普通话,<img src='http://image.tmdb.org/t/p/w185//qJ2t...,Christian Bale|Michael Caine|Heath Ledger|Aaro...,134,81,Christopher Nolan,819.558444,4.430046
14204,14448,19995,Avatar,Enter the World of Pandora.,2009-12-10 00:00:00,Action|Adventure|Fantasy|Science Fiction,Avatar Collection,en,237.0,2787.965087,...,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español,<img src='http://image.tmdb.org/t/p/w185//btnl...,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,83,153,James Cameron,2550.965087,10.763566
17311,17669,24428,The Avengers,Some assembly required.,2012-04-25 00:00:00,Science Fiction|Action|Adventure,The Avengers Collection,en,220.0,1519.557910,...,143.0,When an unexpected enemy emerges and threatens...,English,<img src='http://image.tmdb.org/t/p/w185//RYMX...,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,115,147,Joss Whedon,1299.557910,5.907081
25310,26272,293660,Deadpool,Witness the beginning of a happy ending,2016-02-09 00:00:00,Action|Adventure|Comedy,Deadpool Collection,en,58.0,783.112979,...,108.0,Deadpool tells the origin story of former Spec...,English,<img src='http://image.tmdb.org/t/p/w185//fSRb...,Ryan Reynolds|Morena Baccarin|Ed Skrein|T.J. M...,46,88,Tim Miller,725.112979,12.501948

__Movies Top 5 - Highest Rating__

In [180]:
rating_best = filterMovies(movies,'vote_average',5,False,min_votes=50)
rating_best

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
3959,10233,19404,Dilwale Dulhania Le Jayenge,Come... Fall In Love,1995-10-20 00:00:00,Comedy|Drama|Romance,0,hi,13.2,100.0,...,190.0,"Raj is a rich, carefree, happy-go-lucky second...",हिन्दी,<img src='http://image.tmdb.org/t/p/w185//2CAL...,Shah Rukh Khan|Kajol|Amrish Puri|Anupam Kher|S...,27,30,Aditya Chopra,86.8,6.575758
8514,38503,192040,Planet Earth,planet earth as you've never seen it before,2006-12-10 00:00:00,Documentary,0,en,0.0,0.0,...,550.0,A documentary miniseries described by its make...,English,<img src='http://image.tmdb.org/t/p/w185//koVz...,David Attenborough,1,4,Alastair Fothergill,0.0,0.000000
3343,7578,20532,Sansho the Bailiff,A film of unparalleled beauty by the great Jap...,1954-03-31 00:00:00,Drama,0,ja,0.0,0.0,...,124.0,In medieval Japan a compassionate governor is ...,日本語,<img src='http://image.tmdb.org/t/p/w185//p64i...,Kinuyo Tanaka|Yoshiaki Hanayagi|Kyôko Kagawa|E...,29,17,Kenji Mizoguchi,0.0,0.000000
7703,28846,321640,The Jinx: The Life and Deaths of Robert Durst,Four Decades. Three Murders. And One Very Rich...,2015-02-08 00:00:00,Documentary,0,en,0.0,0.0,...,240.0,"Robert Durst, scion of one of New York’s billi...",English,<img src='http://image.tmdb.org/t/p/w185//jLqQ...,Robert Durst|Andrew Jarecki|Marc Smerling|Zach...,11,9,Andrew Jarecki,0.0,0.000000
8161,32987,359364,Human,Accepting your true identity is accepting who ...,2015-09-12 00:00:00,Documentary,0,fr,13.0,0.0,...,263.0,A combination of first-person stories and excl...,Pусский|ελληνικά|English|Español|Français|Ital...,<img src='http://image.tmdb.org/t/p/w185//vdZg...,Luis Cancu,1,8,Yann Arthus-Bertrand,0.0,0.000000

__Movies Top 5 - Lowest Rating__

In [181]:
rating_worst = filterMovies(movies,'vote_average',5,True,min_votes=100)
rating_worst

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
2135,6665,11059,House of the Dead,You won't last the night.,2003-04-11 00:00:00,Horror|Action|Thriller,House of the Dead Collection,en,7.0,13.818181,...,90.0,"Set on an island off the coast, a techno rave ...",English,<img src='http://image.tmdb.org/t/p/w185//5jBI...,Jonathan Cherry|Tyron Leitso|Clint Howard|Ona ...,17,97,Uwe Boll,6.818181,0.974026
3461,13476,14164,Dragonball Evolution,The legend comes to life.,2009-04-01 00:00:00,Action|Adventure|Fantasy|Science Fiction|Thriller,0,en,100.0,0.000000,...,85.0,The young warrior Son Goku sets out on a quest...,English|日本語|हिन्दी,<img src='http://image.tmdb.org/t/p/w185//23Pc...,Chow Yun-fat|Justin Chatwin|Joon Park|Jamie Ch...,15,6,James Wong,0.000000,0.000000
1381,3439,5491,Battlefield Earth,Take Back The Planet,2000-05-10 00:00:00,Action|Science Fiction|War,0,en,44.0,21.400000,...,118.0,"In the year 3000, man is no match for the Psyc...",English|Français,<img src='http://image.tmdb.org/t/p/w185//wXCR...,John Travolta|Barry Pepper|Forest Whitaker|Kim...,16,12,Roger Christian,-22.600000,-0.513636
2603,9578,12142,Alone in the Dark,Can mankind defeat the army of darkness unleas...,2005-01-28 00:00:00,Action|Fantasy|Horror|Thriller,Alone in the Dark Collection,en,20.0,10.442808,...,96.0,Edward Carnby is a private investigator specia...,English|Português,<img src='http://image.tmdb.org/t/p/w185//tQZb...,Christian Slater|Tara Reid|Stephen Dorff|Frank...,29,13,Uwe Boll,-9.557192,-0.477860
3320,12824,13805,Disaster Movie,Your favorite movies are going to be destroyed.,2008-08-29 00:00:00,Action|Comedy,0,en,25.0,14.109284,...,87.0,"In DISASTER MOVIE, the filmmaking team behind ...",English,<img src='http://image.tmdb.org/t/p/w185//3J8X...,Matt Lanter|Vanessa Lachey|Nicole Ari Parker|C...,15,13,Jason Friedberg,-10.890716,-0.435629

In [182]:
rating_worst = filterMovies(movies,'vote_average',5,True,min_votes=100,min_budget=20)
rating_worst

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
1474,13476,14164,Dragonball Evolution,The legend comes to life.,2009-04-01 00:00:00,Action|Adventure|Fantasy|Science Fiction|Thriller,0,en,100.0,0.000000,...,85.0,The young warrior Son Goku sets out on a quest...,English|日本語|हिन्दी,<img src='http://image.tmdb.org/t/p/w185//23Pc...,Chow Yun-fat|Justin Chatwin|Joon Park|Jamie Ch...,15,6,James Wong,0.000000,0.000000
517,3439,5491,Battlefield Earth,Take Back The Planet,2000-05-10 00:00:00,Action|Science Fiction|War,0,en,44.0,21.400000,...,118.0,"In the year 3000, man is no match for the Psyc...",English|Français,<img src='http://image.tmdb.org/t/p/w185//wXCR...,John Travolta|Barry Pepper|Forest Whitaker|Kim...,16,12,Roger Christian,-22.600000,-0.513636
1402,12824,13805,Disaster Movie,Your favorite movies are going to be destroyed.,2008-08-29 00:00:00,Action|Comedy,0,en,25.0,14.109284,...,87.0,"In DISASTER MOVIE, the filmmaking team behind ...",English,<img src='http://image.tmdb.org/t/p/w185//3J8X...,Matt Lanter|Vanessa Lachey|Nicole Ari Parker|C...,15,13,Jason Friedberg,-10.890716,-0.435629
1021,9578,12142,Alone in the Dark,Can mankind defeat the army of darkness unleas...,2005-01-28 00:00:00,Action|Fantasy|Horror|Thriller,Alone in the Dark Collection,en,20.0,10.442808,...,96.0,Edward Carnby is a private investigator specia...,English|Português,<img src='http://image.tmdb.org/t/p/w185//tQZb...,Christian Slater|Tara Reid|Stephen Dorff|Frank...,29,13,Uwe Boll,-9.557192,-0.477860
757,5378,9544,FearDotCom,The last site you'll ever see.,2002-08-09 00:00:00,Horror|Thriller,0,en,40.0,18.902015,...,101.0,"With four corpses on his hands, New York City ...",English|Pусский,<img src='http://image.tmdb.org/t/p/w185//phcd...,Stephen Dorff|Natascha McElhone|Stephen Rea|Ud...,20,63,William Malone,-21.097985,-0.527450

__Movies Top 5 - Most Popular__

In [183]:
filterMovies(movies,'popularity',5,False)

,index,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
29042,30330,211672,Minions,"Before Gru, they had a history of bad bosses",2015-06-17 00:00:00,Family|Animation|Adventure|Comedy,Despicable Me Collection,en,74.0,1156.730962,...,91.0,"Minions Stuart, Kevin and Bob are recruited by...",English,<img src='http://image.tmdb.org/t/p/w185//tMaG...,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,17,12,Kyle Balda,1082.730962,14.631499
31469,32927,297762,Wonder Woman,Power. Grace. Wisdom. Wonder.,2017-05-30 00:00:00,Action|Adventure|Fantasy,Wonder Woman Collection,en,149.0,820.580447,...,141.0,An Amazon princess comes to the world of Man t...,Deutsch|English,<img src='http://image.tmdb.org/t/p/w185//gfJG...,Gal Gadot|Chris Pine|Robin Wright|Danny Huston...,106,195,Patty Jenkins,671.580447,4.507251
39224,41556,321612,Beauty and the Beast,Be our guest.,2017-03-16 00:00:00,Family|Fantasy|Romance,0,en,160.0,1262.886337,...,129.0,A live-action adaptation of Disney's version o...,English,<img src='http://image.tmdb.org/t/p/w185//tWqi...,Emma Watson|Dan Stevens|Luke Evans|Kevin Kline...,156,115,Bill Condon,1102.886337,6.893040
40457,42940,339403,Baby Driver,All you need is one killer track.,2017-06-28 00:00:00,Action|Crime,0,en,34.0,224.511319,...,113.0,After being coerced into working for a crime b...,English,<img src='http://image.tmdb.org/t/p/w185//rmnQ...,Ansel Elgort|Lily James|Kevin Spacey|Jamie Fox...,56,183,Edgar Wright,190.511319,5.603274
23372,24187,177572,Big Hero 6,From the creators of Wreck-it Ralph and Frozen,2014-10-24 00:00:00,Adventure|Family|Animation|Action|Comedy,0,en,165.0,652.105443,...,102.0,The special bond that develops between plus-si...,English,<img src='http://image.tmdb.org/t/p/w185//xozr...,Scott Adsit|Ryan Potter|Daniel Henney|T.J. Mil...,46,39,Chris Williams,487.105443,2.952154

## Find your next Movie

3. __Filter__ the Dataset for movies that meet the following conditions:

__Search 1: Science Fiction Action Movie with Bruce Willis (sorted from high to low Rating)__

__Search 2: Movies with Uma Thurman and directed by Quentin Tarantino (sorted from short to long runtime)__

__Search 3: Most Successful Pixar Studio Movies between 2010 and 2015 (sorted from high to low Revenue)__

__Search 4: Action or Thriller Movie with original language English and minimum Rating of 7.5 (most recent movies first)__

In [184]:
sciFiMovies = movies[(movies['genres'].str.contains('Science Fiction',case=False,na=False))&movies['genres'].str.contains('Action',case=False,na=False)]
bruce_Wills_SFiMovies = sciFiMovies[sciFiMovies['cast'].str.contains('Bruce Willis',case=False,na=False)]
bruce_Wills_SFiMovies.sort_values(by='vote_average',ascending=False)

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
1448,18,The Fifth Element,There is no future without it.,1997-05-07 00:00:00,Adventure|Fantasy|Action|Thriller|Science Fiction,0,en,90.0,263.920180,Columbia Pictures|Gaumont,...,126.0,"In 2257, a taxi driver is unintentionally give...",English|svenska|Deutsch,<img src='http://image.tmdb.org/t/p/w185//fPtl...,Bruce Willis|Gary Oldman|Ian Holm|Milla Jovovi...,114,134,Luc Besson,173.920180,1.932446
19218,59967,Looper,"Hunted By Your Future, Haunted By Your Past",2012-09-26 00:00:00,Action|Thriller|Science Fiction,0,en,30.0,47.042000,Endgame Entertainment|FilmDistrict|DMG Enterta...,...,118.0,"In the futuristic action thriller Looper, time...",English,<img src='http://image.tmdb.org/t/p/w185//sNjL...,Joseph Gordon-Levitt|Bruce Willis|Emily Blunt|...,34,42,Rian Johnson,17.042000,0.568067
1786,95,Armageddon,The Earth's Darkest Day Will Be Man's Finest Hour,1998-07-01 00:00:00,Action|Thriller|Science Fiction|Adventure,0,en,140.0,553.799566,Jerry Bruckheimer Films|Touchstone Pictures|Va...,...,151.0,When an asteroid threatens to collide with Ear...,English|Pусский,<img src='http://image.tmdb.org/t/p/w185//fMtO...,Bruce Willis|Billy Bob Thornton|Ben Affleck|Li...,67,108,Michael Bay,413.799566,2.955711
14135,19959,Surrogates,How do you save humanity when the only thing t...,2009-09-24 00:00:00,Action|Science Fiction|Thriller,0,en,80.0,122.444772,Touchstone Pictures|Mandeville Films|Wintergre...,...,89.0,Set in a futuristic world where humans live in...,English|Français,<img src='http://image.tmdb.org/t/p/w185//v3Z0...,Bruce Willis|Radha Mitchell|Rosamund Pike|Jame...,44,25,Jonathan Mostow,42.444772,0.530560
20333,72559,G.I. Joe: Retaliation,0,2013-03-26 00:00:00,Adventure|Action|Science Fiction|Thriller,G.I. Joe (Live-Action) Collection,en,130.0,371.876278,Paramount Pictures|Di Bonaventura Pictures|Has...,...,110.0,"Framed for crimes against the country, the G.I...",English,<img src='http://image.tmdb.org/t/p/w185//3rWI...,Dwayne Johnson|D.J. Cotrona|Adrianne Palicki|B...,20,28,Jon M. Chu,241.876278,1.860587
27619,307663,Vice,Where the future is your past.,2015-01-16 00:00:00,Thriller|Science Fiction|Action|Adventure,0,en,10.0,0.000000,Grindstone Entertainment Group|K5 Internationa...,...,96.0,Julian Michaels has designed the ultimate reso...,English,<img src='http://image.tmdb.org/t/p/w185//nPqN...,Ambyr Childers|Thomas Jane|Bryan Greenberg|Bru...,51,56,Brian A Miller,0.000000,0.000000

In [185]:
#Search 2 Uma Thurman with Tarntino sorted from short to long
condition_2 = movies["cast"].str.contains(
        'Uma Thurman',
    na=False,case=False) & movies['director'].str.contains(
        'Tarantino',
        case=False,na=False)
movies[condition_2].sort_values(by='runtime')

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
6667,24,Kill Bill: Vol. 1,Go for the kill.,2003-10-10 00:00:00,Action|Crime,Kill Bill Collection,en,30.0,180.949000,Miramax Films|A Band Apart|Super Cool ManChu,...,111.0,An assassin is shot at the altar by her ruthle...,English|日本語|Français,<img src='http://image.tmdb.org/t/p/w185//v7Ta...,Uma Thurman|Lucy Liu|Vivica A. Fox|Daryl Hanna...,36,161,Quentin Tarantino,150.949000,5.031633
7208,393,Kill Bill: Vol. 2,The bride is back for the final cut.,2004-04-16 00:00:00,Action|Crime|Thriller,Kill Bill Collection,en,30.0,152.159461,Miramax Films|A Band Apart|Super Cool ManChu,...,136.0,The Bride unwaveringly continues on her roarin...,English|普通话|Español|广州话 / 廣州話,<img src='http://image.tmdb.org/t/p/w185//2yhg...,Uma Thurman|David Carradine|Daryl Hannah|Micha...,27,130,Quentin Tarantino,122.159461,4.071982
291,680,Pulp Fiction,Just because you are a character doesn't mean ...,1994-09-10 00:00:00,Thriller|Crime,0,en,8.0,213.928762,Miramax Films|A Band Apart|Jersey Films,...,154.0,"A burger-loving hit man, his philosophical par...",English|Español|Français,<img src='http://image.tmdb.org/t/p/w185//d5iI...,John Travolta|Samuel L. Jackson|Uma Thurman|Br...,54,87,Quentin Tarantino,205.928762,25.741095

In [186]:
movies['release_date'] = movies['release_date'].astype('datetime64[ns]')

In [187]:
#Most Successful pixar movies 2010 -> 2015 By revenue
best_pixar = movies['production_companies'].str.contains(
    'pixar',case=False,na=False)&(movies['release_date'].dt.year>2009)&(
        movies['release_date'].dt.year < 2016
    )
movies[best_pixar].sort_values(by='revenue_musd',ascending=False)

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
15236,10193,Toy Story 3,No toy gets left behind.,2010-06-16,Animation|Family|Comedy,Toy Story Collection,en,200.0,1066.969703,Walt Disney Pictures|Pixar Animation Studios,...,103.0,"Woody, Buzz, and the rest of Andy's toys haven...",English|Español,<img src='http://image.tmdb.org/t/p/w185//amY0...,Tom Hanks|Tim Allen|Ned Beatty|Joan Cusack|Mic...,45,38,Lee Unkrich,866.969703,4.334849
29957,150540,Inside Out,Meet the little voices inside your head.,2015-06-09,Drama|Comedy|Animation|Family,0,en,175.0,857.611174,Walt Disney Pictures|Pixar Animation Studios,...,94.0,"Growing up can be a bumpy road, and it's no ex...",English,<img src='http://image.tmdb.org/t/p/w185//lRHE...,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,65,50,Pete Docter,682.611174,3.900635
20888,62211,Monsters University,School never looked this scary.,2013-06-20,Animation|Family,"Monsters, Inc. Collection",en,200.0,743.559607,Walt Disney Pictures|Pixar Animation Studios,...,104.0,A look at the relationship between Mike and Su...,English,<img src='http://image.tmdb.org/t/p/w185//tyHH...,Billy Crystal|John Goodman|Steve Buscemi|Helen...,24,13,Dan Scanlon,543.559607,2.717798
17220,49013,Cars 2,Ka-ciao!,2011-06-11,Animation|Family|Adventure|Comedy,Cars Collection,en,200.0,559.852396,Walt Disney Pictures|Pixar Animation Studios,...,106.0,Star race car Lightning McQueen and his pal Ma...,English|日本語|Italiano|Français,<img src='http://image.tmdb.org/t/p/w185//okIz...,Owen Wilson|Larry the Cable Guy|Michael Caine|...,47,40,John Lasseter,359.852396,1.799262
18900,62177,Brave,Change your fate.,2012-06-21,Animation|Adventure|Comedy|Family|Action|Fantasy,0,en,185.0,538.983207,Walt Disney Pictures|Pixar Animation Studios,...,93.0,Brave is set in the mystical Scottish Highland...,English,<img src='http://image.tmdb.org/t/p/w185//8l0p...,Kelly Macdonald|Billy Connolly|Emma Thompson|J...,15,44,Brenda Chapman,353.983207,1.913423
30388,105864,The Good Dinosaur,Little Arms With Big Attitude,2015-11-14,Adventure|Animation|Family,0,en,175.0,331.926147,Walt Disney Pictures|Pixar Animation Studios,...,93.0,An epic journey into the world of dinosaurs wh...,English,<img src='http://image.tmdb.org/t/p/w185//8RSk...,Raymond Ochoa|Jack Bright|Jeffrey Wright|Franc...,19,11,Peter Sohn,156.926147,0.896721
25516,141423,The Legend of Mor'du,0,2012-01-01,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,6.0,The witch from Pixar's Brave uses magical illu...,English,<img src='http://image.tmdb.org/t/p/w185//8FKR...,Julie Walters|Steve Purcell|Callum O'Neil,3,7,Brian Larsen,0.000000,0.000000
40259,145316,Air Mater,0,2011-08-04,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,6.0,Mater's decision to fly lands him accidentally...,English,<img src='http://image.tmdb.org/t/p/w185//jDwg...,Larry the Cable Guy|Stacy Keach|Keith Ferguson...,12,4,Rob Gibbs,0.000000,0.000000
34560,345637,Sanjay's Super Team,0,2015-11-25,Animation,0,en,0.0,0.000000,Pixar Animation Studios,...,7.0,Sanjay's Super Team follows the daydream of a ...,English,<img src='http://image.tmdb.org/t/p/w185//mShc...,0,0,4,Sanjay Patel,0.000000,0.000000
31803,286192,Lava,0,2015-06-21,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,7.0,The story follows the love story of two volcan...,English,<img src='http://image.tmdb.org/t/p/w185//blZS...,Napua Greig|Kuana Torres Kahele,2,19,James Ford Murphy,0.000000,0.000000
25517,256835,Toy Story That Time Forgot,0,2014-12-02,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,22.0,"During a post-Christmas play date, the gang fi...",English,<img src='http://image.tmdb.org/t/p/w185//jqQP...,Tom Hanks|Tim Allen|Joan Cusack|Kristen Schaal...,8,4,Steve Purcell,0.000000,0.000000
24254,82424,Small Fry,0,2011-11-23,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,7.0,A fast food restaurant mini variant of Buzz fo...,English,<img src='http://image.tmdb.org/t/p/w185//z096...,Lori Alan|Carlos Alazraqui|Tim Allen|Bob Berge...,20,6,Angus MacLane,0.000000,0.000000
25515,130925,Partysaurus Rex,An Electro Sudsy Good Time!,2012-09-14,Animation|Comedy|Family|Fantasy,0,en,0.0,0.000000,Walt Disney Pictures|Pixar Animation Studios,...,7.0,When Rex finds himself left behind in the bath...,English,<img src='http://image.tmdb.org/t/p/w185//ylj9...,Tom Hanks|Tim Allen|Wallace Shawn|Corey Burton...,28,13,Mark A. Walsh,0.000000,0.000000
16392,40619,Day & Night,0,2010-06-17,Animation|Family,0,en,0.0,0.000000,Walt Disney Pictures|Pixar Animation Studios,...,6.0,"When Day, a sunny fellow, encounters Night, a ...",0,<img src='http://image.tmdb.org/t/p/w185//eQ1Q...,Wayne Dyer,1,1,Teddy Newton,0.000000,0.000000
24252,77887,Hawaiian Vacation,0,2011-06-16,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,6.0,The toys throw Ken and Barbie a Hawaiian vacat...,English,<img src='http://image.tmdb.org/t/p/w185//tByW...,Tim Allen|Jodi Benson|Blake Clark|Tom Hanks|Jo...,21,8,Gary Rydstrom,0.000000,0.000000
22489,83564,La luna,A young boy discovers his family's most unusua...,2011-01-01,Animation|Family,0,en,0.0,0.000000,Pixar Animation Studios,...,7.0,A young boy comes of age in the most peculiar ...,English,<img src='http://image.tmdb.org/t/p/w185//iS6D...,Krista Sheffler|Tony Fucile|Phil Sheridan,3,9,Enrico Casarosa,0.000000,0.000000
21697,213121,Toy Story of Terror!,One toy gets left behind!,2013-10-15,Animation|Comedy|Family,0,en,0.0,0.000000,Walt Disney Pictures|Pixar Animation Studios,...,22.0,What starts out as a fun road trip for the Toy...,English,<img src='http://image.tmdb.org/t/p/w185//aNDr...,Tom Hanks|Tim Allen|Kristen Schaal|Carl Weathe...,8,8,Angus MacLane,0.000000,0.000000
21694,200481,The Blue Umbrella,0,2013-02-12,Animation|Romance,0,en,0.0,0.000000,Pixar Animation Studios,...,7.0,It is just another evening commute until the r...,No Language,<img src='http://image.tmdb.org/t/p/w185//iSWV...,Sarah Jaffe,1,1,Saschka Unseld,0.000000,0.000000
40675,355338,Riley's First Date?,0,2015-11-03,Animation|Family,0,en,0.0,0.000000,Walt Disney Pictures|Pixar Animation Studios,...,5.0,"Riley, now 12, is hanging out at home with her...",English,<img src='http://image.tmdb.org/t/p/w185//pyry...,Amy Poehler|Phyllis Smith|Bill Hader|Lewis Bla...,20,4,Josh Cooley,0.000000,0.000000

In [188]:
movies['original_language'].head()

0    en
1    en
2    en
3    en
4    en
Name: original_language, dtype: object

In [189]:
#Search 4: Action or Thriller Movie with original language English 
# and minimum Rating of 7.5 (most recent movies first)
condition_4 = (movies['genres'].str.contains(
    'Action',case=False,na=False
)|movies['genres'].str.contains('Thriller',case=False,na=False))&(
    movies['original_language'] == 'en'
)&(movies['vote_average']>=7.5)
movies[condition_4].sort_values(by= 'release_date',ascending = False)

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,...,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director,profit,ROI
44490,417320,Descendants 2,Long live evil.,2017-07-21,TV Movie|Family|Action|Comedy|Music|Adventure,Descendants Collection,en,0.00,0.000000,Walt Disney Television,...,111.0,When the pressure to be royal becomes too much...,Dansk,<img src='http://image.tmdb.org/t/p/w185//8BNy...,Dove Cameron|Sofia Carson|Cameron Boyce|Booboo...,17,3,Kenny Ortega,0.000000,0.000000
43941,374720,Dunkirk,The event that shaped our world,2017-07-19,Action|Drama|History|Thriller|War,0,en,100.00,519.876949,Canal+|Studio Canal|Warner Bros.|Syncopy|RatPa...,...,107.0,The miraculous evacuation of Allied soldiers f...,English|Français|Deutsch,<img src='http://image.tmdb.org/t/p/w185//ebSn...,Fionn Whitehead|Tom Glynn-Carney|Jack Lowden|H...,66,214,Christopher Nolan,419.876949,4.198769
42624,382614,The Book of Henry,Never leave things undone.,2017-06-16,Thriller|Drama|Crime,0,en,10.00,4.219536,Sidney Kimmel Entertainment|Double Nickel Ente...,...,105.0,"Naomi Watts stars as Susan, a single mother of...",English,<img src='http://image.tmdb.org/t/p/w185//suLF...,Naomi Watts|Jaeden Lieberher|Jacob Tremblay|Sa...,27,27,Colin Trevorrow,-5.780464,-0.578046
26273,283995,Guardians of the Galaxy Vol. 2,Obviously.,2017-04-19,Action|Adventure|Comedy|Science Fiction,Guardians of the Galaxy Collection,en,200.00,863.416141,Walt Disney Pictures|Marvel Studios,...,137.0,The Guardians must fight to keep their newfoun...,English,<img src='http://image.tmdb.org/t/p/w185//y4MB...,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,63,131,James Gunn,663.416141,3.317081
43467,416445,Revengeance,Revenge is a dish best served animated,2017-04-05,Comedy|Action|Animation,0,en,0.00,0.000000,Plymptoons,...,71.0,"A low-rent bounty hunter named Rod Rosse, The ...",English,<img src='http://image.tmdb.org/t/p/w185//p4St...,Charley Rossman|Robert LuJane,2,2,Bill Plympton,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11135,44892,The Music Box,Mr. Laurel and Mr. Hardy decided to reorganize...,1932-04-16,Action|Comedy,0,en,0.00,0.000000,Hal Roach Studios,...,29.0,The Laurel &amp; Hardy Moving Co. have a chall...,English,<img src='http://image.tmdb.org/t/p/w185//qWVG...,Stan Laurel|Oliver Hardy|Dinah|Gladys Gale|Bil...,9,9,James Parrott,0.000000,0.000000
8268,877,Scarface,The rise and fall of a power hungry mobster.,1932-04-09,Action|Adventure|Crime|Drama|Thriller,0,en,0.00,0.600000,United Artists|The Caddo Company,...,90.0,"Big Louis Costillo, last of the old-style gang...",English|Italiano,<img src='http://image.tmdb.org/t/p/w185//bnFj...,Paul Muni|Ann Dvorak|Karen Morley|Osgood Perki...,41,22,Howard Hawks,0.000000,0.000000
8255,25768,"Steamboat Bill, Jr.",The Laugh Special of the Age. See It.,1928-02-14,Action|Comedy,0,en,0.00,0.000000,Buster Keaton Productions,...,70.0,The just out of college effete son of a no-non...,0,<img src='http://image.tmdb.org/t/p/w185//5cY9...,Buster Keaton|Ernest Torrence|Tom McGuire|Mari...,6,12,Buster Keaton,0.000000,0.000000
2879,961,The General,"Buster drives ""The General"" to trainload of la...",1926-12-31,Action|Adventure|Comedy|Drama,0,en,0.75,0.000000,Buster Keaton Productions|Joseph M. Schenck Pr...,...,79.0,During America’s Civil War Union spies steal e...,English,<img src='http://image.tmdb.org/t/p/w185//wZ9R...,Buster Keaton|Marion Mack|Glen Cavender|Jim Fa...,22,25,Buster Keaton,0.000000,0.000000
34547,128899,Bardelys the Magnificent,The screen's great lover in a dashing role!,1926-09-30,Action|Drama|Romance,0,en,0.00,0.000000,Metro-Goldwyn-Mayer (MGM),...,90.0,Rafael Sabatini's story of the swashbuckling e...,English,<img src='http://image.tmdb.org/t/p/w185//9d2W...,John Gilbert|Eleanor Boardman|Roy D'Arcy|Lione...,6,11,King Vidor,0.000000,0.000000

## Are Franchises more successful?

4. __Analyze__ the Dataset and __find out whether Franchises (Movies that belong to a collection) are more successful than stand-alone movies__ in terms of:

- mean revenue
- median Return on Investment
- mean budget raised
- mean popularity
- mean rating

hint: use groupby()

In [161]:
movies["belongs_to_collection"]=movies["belongs_to_collection"].replace({0:'Standalone'})
df_franshise = movies
df_franshise["belongs_to_collection"] = df_franshise["belongs_to_collection"].apply(lambda x : "Standalone" if x == "Standalone" else "Franshise")
df_franshise["belongs_to_collection"].value_counts()

belongs_to_collection
Standalone    40228
Franshise      4463
Name: count, dtype: int64

__Franchise vs. Stand-alone: Average Revenue__

In [162]:
df_franshise.groupby("belongs_to_collection")["revenue_musd"].mean()

belongs_to_collection
Franshise     54.914277
Standalone     6.568834
Name: revenue_musd, dtype: float64

__Franchise vs. Stand-alone: Return on Investment / Profitability (median)__

In [163]:
df_franshise.groupby("belongs_to_collection")["ROI"].mean()

belongs_to_collection
Franshise     234.215651
Standalone    718.390320
Name: ROI, dtype: float64

__Franchise vs. Stand-alone: Average Budget__

In [164]:
df_franshise.groupby("belongs_to_collection")["budget_musd"].mean()

belongs_to_collection
Franshise     13.583240
Standalone     3.262483
Name: budget_musd, dtype: float64

__Franchise vs. Stand-alone: Average Popularity__

In [165]:
df_franshise.groupby("belongs_to_collection")["popularity"].mean()

belongs_to_collection
Franshise     6.245051
Standalone    2.592726
Name: popularity, dtype: float64

__Franchise vs. Stand-alone: Average Rating__

In [166]:
df_franshise.groupby("belongs_to_collection")["vote_average"].mean()

belongs_to_collection
Franshise     5.883397
Standalone    5.626554
Name: vote_average, dtype: float64

## Most Successful Franchises

In [217]:
movies["belongs_to_collection"].value_counts()
franshise_movies = movies[movies["belongs_to_collection"]!=0]
franshise_movies["belongs_to_collection"].value_counts()
franshise = franshise_movies.groupby("belongs_to_collection").agg({"title":"count", "budget_musd": ["sum", "mean"], 
                                                      "revenue_musd": ["sum", "mean"],
                                                      "vote_average": "mean", "popularity": "mean",
                                                      "ROI":"median", 
                                                      "vote_count":"mean"})

5. __Find__ the __most successful Franchises__ in terms of

- __total number of movies__
- __total & mean budget__
- __total & mean revenue__
- __mean rating__

In [212]:
#number of movies 
[franshise_movies["belongs_to_collection"].value_counts().idxmax()]

['The Bowery Boys']

In [218]:
franshise.nlargest(20,("revenue_musd","mean"))

                                    title budget_musd              \
                                    count         sum        mean
belongs_to_collection
Avatar Collection                       1      237.00  237.000000
The Avengers Collection                 2      500.00  250.000000
Finding Nemo Collection                 2      294.00  147.000000
The Hobbit Collection                   3      750.00  250.000000
The Lord of the Rings Collection        3      266.00   88.666667
Harry Potter Collection                 8     1280.00  160.000000
Star Wars Collection                    8      854.35  106.793750
Pirates of the Caribbean Collection     5     1250.00  250.000000
The Secret Life of Pets Collection      1       75.00   75.000000
Transformers Collection                 5      965.00  193.000000
Spider-Man Collection                   3      597.00  199.000000
The Dark Knight Collection              3      585.00  195.000000
Wonder Woman Collection                 1      149.00  149.000000
Guardians of the Galaxy Collection      2      370.00  185.000000
Fantastic Beasts Collection             1      180.00  180.000000
Iron Man Collection                     3      540.00  180.000000
Deadpool Collection                     1       58.00   58.000000
Man of Steel Collection                 2      475.00  237.500000
Jurassic Park Collection                4      379.00   94.750000
Captain America Collection              3      560.00  186.666667

                                    revenue_musd              vote_average  \
                                             sum         mean         mean
belongs_to_collection
Avatar Collection                    2787.965087  2787.965087     7.200000
The Avengers Collection              2924.961604  1462.480802     7.350000
Finding Nemo Collection              1968.906425   984.453213     7.200000
The Hobbit Collection                2935.523356   978.507785     7.233333
The Lord of the Rings Collection     2916.544743   972.181581     8.033333
Harry Potter Collection              7707.367425   963.420928     7.537500
Star Wars Collection                 7434.494790   929.311849     7.375000
Pirates of the Caribbean Collection  4521.576826   904.315365     6.880000
The Secret Life of Pets Collection    875.457937   875.457937     5.900000
Transformers Collection              4366.101244   873.220249     6.140000
Spider-Man Collection                2496.346518   832.115506     6.466667
The Dark Knight Collection           2463.716216   821.238739     7.800000
Wonder Woman Collection               820.580447   820.580447     7.200000
Guardians of the Galaxy Collection   1636.744770   818.372385     7.750000
Fantastic Beasts Collection           809.342332   809.342332     7.200000
Iron Man Collection                  2424.547547   808.182516     6.933333
Deadpool Collection                   783.112979   783.112979     7.400000
Man of Steel Collection              1536.105712   768.052856     6.100000
Jurassic Park Collection             3031.484143   757.871036     6.500000
Captain America Collection           2238.640841   746.213614     7.100000

                                     popularity        ROI    vote_count
                                           mean     median          mean
belongs_to_collection
Avatar Collection                    185.070892  10.763566  12114.000000
The Avengers Collection               63.633534   4.963190   9454.000000
Finding Nemo Collection               19.987735   6.573212   5312.500000
The Hobbit Collection                 25.205614   2.833600   5981.333333
The Lord of the Rings Collection      30.272873  10.725157   8253.000000
Harry Potter Collection               26.253893   5.165086   5983.250000
Star Wars Collection                  23.410919   7.239637   5430.375000
Pirates of the Caribbean Collection   53.972237   2.453009   5016.000000
The Secret Life of Pets Collection    11.013950  10.672772   3536.000000
Transformers Collection               14.425077   4.197167   3046.400000
Spider-Man Collection                 22.620704   2.918832   4505.666667
The Dark Knight Collection            57.418393   3.339756   9681.000000
Wonder Woman Collection              294.337037   4.507251   5025.000000
Guardians of the Galaxy Collection   119.311296   3.433036   7436.000000
Fantastic Beasts Collection           41.051421   3.496346   5612.000000
Iron Man Collection                   21.625895   3.179816   8290.333333
Deadpool Collection                  187.860492  12.501948  11444.000000
Man of Steel Collection               24.987357   2.219510   6825.500000
Jurassic Park Collection              10.772810   6.027789   4608.750000
Captain America Collection            61.307807   3.204509   6839.000000

belongs_to_collection    식객 시리즈
budget_musd               250.0
dtype: object

## Most Successful Directors

6. __Find__ the __most successful Directors__ in terms of

- __total number of movies__
- __total revenue__
- __mean rating__

In [228]:
directors = movies.groupby("director").agg({"title": "count", "vote_average" :"mean", "vote_count": "sum"})

In [222]:
movies['director'].head(10)

0      John Lasseter
1       Joe Johnston
2      Howard Deutch
3    Forest Whitaker
4      Charles Shyer
5       Michael Mann
6     Sydney Pollack
7       Peter Hewitt
8        Peter Hyams
9    Martin Campbell
Name: director, dtype: object

In [229]:
directors[(directors.vote_count >= 10000) & (directors.title >= 10)].nlargest(20, "vote_average")

                   title  vote_average  vote_count
director
Hayao Miyazaki        14      7.700000     14700.0
Christopher Nolan     11      7.618182     67344.0
Quentin Tarantino     10      7.490000     45910.0
Wes Anderson          10      7.370000     11743.0
David Fincher         10      7.350000     37588.0
Peter Jackson         13      7.138462     47571.0
Martin Scorsese       39      7.033333     35541.0
Joel Coen             17      7.023529     18139.0
James Cameron         11      6.927273     33736.0
Stanley Kubrick       16      6.912500     18214.0
James Mangold         10      6.900000     16607.0
Steven Spielberg      33      6.893939     62266.0
Danny Boyle           14      6.871429     16504.0
Guy Ritchie           10      6.800000     19626.0
Robert Zemeckis       19      6.794737     37666.0
Terry Gilliam         14      6.764286     10049.0
Tim Burton            21      6.733333     36922.0
John Lasseter         10      6.720000     18337.0
Ang Lee               14      6.714286     11164.0
Antoine Fuqua         12      6.708333     15519.0